[build]
  bin = "bin/main"
  cmd = "go run github.com/a-h/templ/cmd/templ@v0.2.697 generate && go build -o ./bin/main ."
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  exclude_regex = [".*_templ.go"]
